# Seed data for IELTS vocabulary
# Each entry: (word, part_of_speech, definition, synonym, example_sentence, difficulty)

CATEGORIES = [
    {"name": "Environment", "slug": "environment", "description": "IELTS vocabulary related to environmental issues, climate change, and nature.", "order": 1},
    {"name": "Education", "slug": "education", "description": "Vocabulary for discussing educational systems, learning, and academic topics.", "order": 2},
    {"name": "Technology", "slug": "technology", "description": "Words about technology, digital transformation, and modern innovations.", "order": 3},
    {"name": "Health", "slug": "health", "description": "Health, medical, and well-being vocabulary for IELTS.", "order": 4},
    {"name": "Economy & Work", "slug": "economy-work", "description": "Economic terms, business vocabulary, and workplace language.", "order": 5},
    {"name": "Society & Culture", "slug": "society-culture", "description": "Social issues, cultural topics, and community-related vocabulary.", "order": 6},
    {"name": "Travel & Tourism", "slug": "travel-tourism", "description": "Travel, tourism, and exploration vocabulary.", "order": 7},
    {"name": "Science & Research", "slug": "science-research", "description": "Scientific terms, research methodology, and academic vocabulary.", "order": 8},
    {"name": "People & Personality", "slug": "people-personality", "description": "Words to describe people's traits, behaviors, and characteristics.", "order": 9},
    {"name": "Emotions & Feelings", "slug": "emotions-feelings", "description": "Emotional vocabulary for expressing feelings and reactions.", "order": 10},
    {"name": "Academic & Formal", "slug": "academic-formal", "description": "Formal and academic words essential for IELTS Writing and Reading.", "order": 11},
    {"name": "Actions & Verbs", "slug": "actions-verbs", "description": "Common academic verbs and their synonyms for IELTS.", "order": 12},
    {"name": "Politics & Government", "slug": "politics-government", "description": "Political systems, government structures, and policy vocabulary.", "order": 13},
    {"name": "Crime & Law", "slug": "crime-law", "description": "Legal terminology, crime types, and justice system vocabulary.", "order": 14},
    {"name": "Task 1 Trends", "slug": "task1-trends", "description": "Language for describing trends, charts, and data in IELTS Writing Task 1.", "order": 15},
    {"name": "Speaking Fluency", "slug": "speaking-fluency", "description": "Useful phrases and linking words for IELTS Speaking fluency.", "order": 16},
]

ENVIRONMENT = [
    ("sustainable", "adjective", "able to be maintained at a certain rate or level", "eco-friendly", "The government promoted sustainable energy sources like solar and wind power.", "advanced"),
    ("biodiversity", "noun", "the variety of plant and animal life in a habitat", "biological diversity", "Deforestation poses a serious threat to biodiversity in tropical regions.", "advanced"),
    ("conservation", "noun", "the protection of natural resources", "preservation", "Wildlife conservation efforts have helped protect endangered species.", "advanced"),
    ("ecosystem", "noun", "a biological community of interacting organisms", "biome", "The Amazon rainforest is one of the most diverse ecosystems on Earth.", "advanced"),
    ("emission", "noun", "the production and discharge of something, especially gas", "discharge", "Carbon emissions from factories contribute to global warming.", "intermediate"),
    ("renewable", "adjective", "able to be replenished naturally", "replenishable", "Investing in renewable energy is crucial for our future.", "intermediate"),
    ("deforestation", "noun", "the action of clearing a wide area of trees", "clearing", "Deforestation in the Amazon has reached alarming levels.", "advanced"),
    ("pollutant", "noun", "a substance that pollutes the environment", "contaminant", "Industrial pollutants are harming local water sources.", "intermediate"),
    ("climate", "noun", "the weather conditions prevailing in an area over a long period", "weather pattern", "Climate change is one of the most pressing issues of our time.", "beginner"),
    ("extinction", "noun", "the state of a species no longer existing", "dying out", "Many species are on the brink of extinction due to habitat loss.", "advanced"),
    ("fossil_fuel", "noun", "a natural fuel such as coal or gas formed from organic remains", "hydrocarbon fuel", "The world needs to reduce its reliance on fossil fuels.", "intermediate"),
    ("greenhouse_effect", "noun", "the trapping of heat in the atmosphere by gases", "warming effect", "The greenhouse effect is intensified by human activities.", "advanced"),
    ("recycle", "verb", "convert waste into reusable material", "reuse", "Households should recycle plastic, glass, and paper waste.", "beginner"),
    ("contamination", "noun", "the action of making something impure", "pollution", "Water contamination affects millions of people worldwide.", "intermediate"),
    ("habitat", "noun", "the natural home of an animal or plant", "environment", "Urban development is destroying natural habitats.", "intermediate"),
    ("ozone", "noun", "a layer in the stratosphere that absorbs UV radiation", "ozone layer", "The ozone layer has been recovering since the ban on CFCs.", "advanced"),
    ("carbon_footprint", "noun", "the amount of CO2 released by an activity or person", "environmental impact", "Using public transport reduces your carbon footprint.", "intermediate"),
    ("conservationist", "noun", "a person who advocates for the protection of the environment", "environmentalist", "Conservationists are working to protect the coral reefs.", "advanced"),
]

EDUCATION = [
    ("curriculum", "noun", "the subjects making up a course of study", "syllabus", "The school curriculum should include more practical skills.", "intermediate"),
    ("pedagogy", "noun", "the method and practice of teaching", "teaching method", "Modern pedagogy emphasizes student-centered learning.", "advanced"),
    ("literacy", "noun", "the ability to read and write", "reading and writing skills", "Improving literacy rates is a priority for developing nations.", "intermediate"),
    ("tuition", "noun", "teaching or instruction, especially in a small group", "instruction", "Many students rely on private tuition to prepare for exams.", "intermediate"),
    ("scholarship", "noun", "a grant to support a student's education", "educational grant", "She won a scholarship to study at Cambridge University.", "intermediate"),
    ("compulsory", "adjective", "required by law or rule", "mandatory", "Secondary education is compulsory in most countries.", "intermediate"),
    ("vocational", "adjective", "relating to an occupation or employment", "career-focused", "Vocational training provides practical skills for specific jobs.", "intermediate"),
    ("academic", "adjective", "relating to education and scholarship", "scholarly", "Academic writing requires formal vocabulary and structure.", "beginner"),
    ("enrolment", "noun", "the action of registering for a course", "registration", "University enrolment numbers have increased this year.", "intermediate"),
    ("assess", "verb", "evaluate or estimate the quality of something", "evaluate", "Teachers assess students through exams and assignments.", "intermediate"),
    ("graduate", "noun", "a person who has completed a course of study", "alumnus", "Graduates with technical skills are in high demand.", "beginner"),
    ("diploma", "noun", "a certificate awarded for completing a course", "qualification", "A diploma in IT can improve your job prospects.", "intermediate"),
    ("specialize", "verb", "focus on a particular area of study", "major in", "Students can specialize in their chosen field in the final year.", "intermediate"),
    ("undergraduate", "noun", "a student studying for a first degree", "bachelor's student", "Undergraduate students often live on campus.", "intermediate"),
    ("postgraduate", "adjective", "relating to study after a bachelor's degree", "graduate-level", "She is pursuing postgraduate studies in public health.", "advanced"),
    ("critical_thinking", "noun", "the objective analysis of facts to form a judgment", "analytical reasoning", "Universities should foster critical thinking skills.", "advanced"),
]

TECHNOLOGY = [
    ("innovation", "noun", "a new method, idea, or product", "invention", "Technological innovation has transformed the way we communicate.", "intermediate"),
    ("digital", "adjective", "relating to computer technology", "electronic", "The digital revolution has changed every aspect of our lives.", "beginner"),
    ("automation", "noun", "the use of machines to perform tasks automatically", "mechanization", "Automation may lead to job losses in manufacturing.", "intermediate"),
    ("artificial_intelligence", "noun", "the simulation of human intelligence by machines", "machine intelligence", "Artificial intelligence is used in medical diagnosis.", "advanced"),
    ("algorithm", "noun", "a process or set of rules to be followed in calculations", "procedure", "Search engines use complex algorithms to rank results.", "advanced"),
    ("cybersecurity", "noun", "the practice of protecting systems from digital attacks", "information security", "Companies invest heavily in cybersecurity measures.", "advanced"),
    ("disruptive", "adjective", "causing significant change to an industry", "transformative", "Disruptive technologies like blockchain are changing finance.", "advanced"),
    ("encryption", "noun", "the process of converting data into a coded form", "coding", "Encryption protects sensitive information online.", "advanced"),
    ("infrastructure", "noun", "the basic physical systems of a society or organization", "framework", "Digital infrastructure is essential for modern economies.", "intermediate"),
    ("interface", "noun", "the means by which users interact with a system", "user interface", "A clean interface improves the user experience.", "intermediate"),
    ("optimize", "verb", "make something as effective as possible", "improve", "Companies optimize their websites for mobile users.", "intermediate"),
    ("programming", "noun", "the process of writing computer code", "coding", "Learning programming is a valuable skill in today's job market.", "beginner"),
    ("sophisticated", "adjective", "complex and advanced", "advanced", "Modern smartphones are sophisticated devices.", "intermediate"),
    ("virtual", "adjective", "not physically existing but simulated by software", "digital", "Virtual classrooms have become common since the pandemic.", "intermediate"),
    ("breakthrough", "noun", "a sudden important discovery or development", "discovery", "The medical breakthrough could save millions of lives.", "advanced"),
]

HEALTH = [
    ("nutrition", "noun", "the process of providing food necessary for health", "nourishment", "Good nutrition is essential for maintaining a healthy lifestyle.", "intermediate"),
    ("epidemic", "noun", "a widespread occurrence of a disease", "outbreak", "The government took measures to control the epidemic.", "intermediate"),
    ("immunization", "noun", "the process of making someone immune to a disease", "vaccination", "Childhood immunization programs have saved countless lives.", "advanced"),
    ("diagnosis", "noun", "the identification of an illness", "identification", "Early diagnosis of cancer greatly improves survival rates.", "intermediate"),
    ("therapy", "noun", "treatment to relieve or cure a disorder", "treatment", "Physical therapy helps patients recover from injuries.", "intermediate"),
    ("preventive", "adjective", "designed to prevent something from happening", "precautionary", "Preventive healthcare reduces long-term medical costs.", "intermediate"),
    ("chronic", "adjective", "persisting for a long time", "long-term", "Chronic diseases like diabetes require ongoing management.", "advanced"),
    ("obesity", "noun", "the condition of being severely overweight", "excessive fatness", "Obesity rates have risen dramatically in recent decades.", "intermediate"),
    ("mental_health", "noun", "a person's psychological and emotional wellbeing", "psychological health", "Mental health should be taken as seriously as physical health.", "intermediate"),
    ("wellbeing", "noun", "the state of being comfortable and happy", "welfare", "Yoga and meditation can improve overall wellbeing.", "intermediate"),
    ("hygiene", "noun", "conditions to maintain health and prevent disease", "cleanliness", "Proper hygiene is essential in preventing the spread of germs.", "beginner"),
    ("remedy", "noun", "a medicine or treatment for a disease", "cure", "Herbal remedies have been used for centuries.", "intermediate"),
    ("symptom", "noun", "a physical or mental feature indicating a condition", "indication", "Common symptoms of the flu include fever and fatigue.", "beginner"),
    ("epidemiology", "noun", "the study of disease distribution", "disease study", "Epidemiology played a crucial role during the pandemic.", "advanced"),
    ("healthcare", "noun", "the organized provision of medical care", "medical services", "Universal healthcare is a priority for many governments.", "intermediate"),
]

ECONOMY_WORK = [
    ("inflation", "noun", "the general increase in prices over time", "price rise", "Inflation affects the purchasing power of consumers.", "intermediate"),
    ("recession", "noun", "a period of economic decline", "downturn", "Many businesses closed during the economic recession.", "intermediate"),
    ("unemployment", "noun", "the state of being without a job", "joblessness", "The government introduced programs to reduce unemployment.", "intermediate"),
    ("investment", "noun", "the act of putting money into something for profit", "funding", "Foreign investment can boost a country's economy.", "beginner"),
    ("entrepreneur", "noun", "a person who starts a business taking financial risks", "business person", "Entrepreneurs drive innovation and create new jobs.", "advanced"),
    ("globalization", "noun", "the process of increasing international interconnectedness", "global integration", "Globalization has led to increased trade between countries.", "advanced"),
    ("subsidy", "noun", "money granted by the government to support an industry", "financial aid", "Farmers receive subsidies to maintain crop production.", "advanced"),
    ("commodity", "noun", "a raw material that can be bought and sold", "goods", "Oil is one of the most traded commodities worldwide.", "intermediate"),
    ("wage", "noun", "a fixed regular payment for work", "salary", "The minimum wage has increased to keep up with living costs.", "beginner"),
    ("productivity", "noun", "the rate at which goods are produced", "efficiency", "Technology has significantly improved workplace productivity.", "intermediate"),
    ("revenue", "noun", "the income generated from business activities", "income", "The company's annual revenue exceeded one billion dollars.", "intermediate"),
    ("budget", "noun", "an estimate of income and expenditure", "financial plan", "The government announced its annual budget last week.", "beginner"),
    ("stakeholder", "noun", "a person with an interest in a business", "interested party", "All stakeholders should be consulted before major decisions.", "advanced"),
    ("outsource", "verb", "obtain work from an external supplier", "contract out", "Many companies outsource customer service to other countries.", "advanced"),
    ("merger", "noun", "the combination of two companies", "union", "The merger created the largest telecom company in the region.", "advanced"),
    ("retail", "noun", "the sale of goods to the public", "selling", "Online retail has grown significantly over the past decade.", "intermediate"),
]

SOCIETY_CULTURE = [
    ("demographics", "noun", "statistical data about a population", "population statistics", "Demographics show an aging population in many developed countries.", "advanced"),
    ("urbanization", "noun", "the increasing population in cities", "city growth", "Urbanization has led to the expansion of major cities.", "advanced"),
    ("inequality", "noun", "the state of being unequal", "disparity", "Income inequality is a growing concern in modern societies.", "intermediate"),
    ("multicultural", "adjective", "relating to many different cultures", "diverse", "Australia is a multicultural society with people from many backgrounds.", "intermediate"),
    ("migration", "noun", "the movement of people to a new area", "relocation", "Economic migration is driven by the search for better opportunities.", "intermediate"),
    ("discrimination", "noun", "unfair treatment based on group membership", "prejudice", "Laws exist to prevent discrimination in the workplace.", "intermediate"),
    ("integration", "noun", "the process of becoming part of a community", "inclusion", "Integration programs help immigrants adapt to their new country.", "advanced"),
    ("poverty", "noun", "the state of being extremely poor", "destitution", "Education is key to breaking the cycle of poverty.", "beginner"),
    ("generation", "noun", "all people born around the same time", "age group", "Each generation has its own unique characteristics and challenges.", "beginner"),
    ("diversity", "noun", "the state of having a variety of people or things", "variety", "Workplace diversity brings fresh perspectives and ideas.", "intermediate"),
    ("welfare", "noun", "the health, happiness, and prosperity of people", "social support", "Welfare programs provide assistance to those in need.", "intermediate"),
    ("community", "noun", "a group of people living in the same place", "neighbourhood", "Community involvement is important for social cohesion.", "beginner"),
    ("standard_of_living", "noun", "the level of comfort and wealth of a person or group", "quality of life", "The standard of living has improved significantly in the last century.", "intermediate"),
    ("censorship", "noun", "the suppression of speech or other public communication", "restriction", "Censorship of the internet is a controversial issue.", "advanced"),
    ("civil_rights", "noun", "the rights of citizens to political and social freedom", "human rights", "The civil rights movement fought for equality and justice.", "advanced"),
]

TRAVEL_TOURISM = [
    ("destination", "noun", "the place to where someone is going", "target location", "Paris is one of the most popular tourist destinations.", "beginner"),
    ("itinerary", "noun", "a planned route or journey", "travel plan", "Our itinerary includes visits to three major cities.", "intermediate"),
    ("accommodation", "noun", "a place to stay or live", "lodging", "Finding affordable accommodation in the city center is difficult.", "intermediate"),
    ("heritage", "noun", "cultural traditions and historical sites", "legacy", "The ancient ruins are part of our world heritage.", "intermediate"),
    ("ecotourism", "noun", "tourism directed toward natural environments", "green tourism", "Ecotourism helps preserve natural habitats while supporting local economies.", "advanced"),
    ("excursion", "noun", "a short trip for pleasure", "outing", "The excursion to the national park was the highlight of our trip.", "intermediate"),
    ("hospitality", "noun", "the friendly reception of guests", "welcome", "The hospitality industry is a major employer in many countries.", "intermediate"),
    ("landmark", "noun", "a recognizable natural or artificial feature", "monument", "The Eiffel Tower is the most famous landmark in Paris.", "beginner"),
    ("authentic", "adjective", "genuine and original", "real", "Tourists seek authentic cultural experiences.", "intermediate"),
    ("cosmopolitan", "adjective", "familiar with many cultures", "multicultural", "London is a cosmopolitan city with a diverse population.", "advanced"),
    ("expedition", "noun", "a journey with a particular purpose", "exploration", "The expedition to the Arctic studied climate change effects.", "advanced"),
    ("souvenir", "noun", "a thing kept as a memory of a place", "memento", "I bought a souvenir from every city I visited.", "beginner"),
    ("immerse", "verb", "to involve oneself deeply in something", "engage", "It is best to immerse yourself in the local culture when traveling.", "intermediate"),
    ("sightseeing", "noun", "the activity of visiting interesting places", "touring", "We spent the first day sightseeing around the old town.", "beginner"),
]

SCIENCE_RESEARCH = [
    ("hypothesis", "noun", "a proposed explanation for something", "theory", "The scientists tested their hypothesis through experiments.", "advanced"),
    ("empirical", "adjective", "based on observation or experience", "evidence-based", "Empirical research is essential for scientific progress.", "advanced"),
    ("methodology", "noun", "a system of methods used in research", "approach", "The research methodology included surveys and interviews.", "advanced"),
    ("analysis", "noun", "detailed examination of data", "examination", "The data analysis revealed significant trends.", "intermediate"),
    ("phenomenon", "noun", "a fact or event that can be observed", "occurrence", "The Northern Lights are a natural phenomenon.", "intermediate"),
    ("laboratory", "noun", "a room for scientific experiments", "lab", "The laboratory is equipped with state-of-the-art equipment.", "beginner"),
    ("experiment", "noun", "a scientific procedure to test a hypothesis", "test", "The experiment was repeated several times to verify the results.", "beginner"),
    ("correlation", "noun", "a mutual relationship between two variables", "connection", "There is a strong correlation between exercise and health.", "advanced"),
    ("variable", "noun", "an element that can change in an experiment", "factor", "Temperature was a key variable in the experiment.", "advanced"),
    ("publication", "noun", "the act of making research public", "release", "The research findings were submitted for publication.", "intermediate"),
    ("statistical", "adjective", "relating to the use of statistics", "numerical", "Statistical analysis confirmed the significance of the results.", "advanced"),
    ("peer_review", "noun", "evaluation by experts in the same field", "expert review", "Peer review ensures the quality of academic research.", "advanced"),
    ("replicate", "verb", "to repeat an experiment to verify results", "reproduce", "Other scientists should be able to replicate the findings.", "advanced"),
    ("evidence", "noun", "facts indicating whether something is true", "proof", "There is strong evidence linking smoking to lung cancer.", "beginner"),
]

PEOPLE_PERSONALITY = [
    ("arrogant", "adjective", "having an exaggerated sense of importance", "haughty", "He was too arrogant to listen to anyone's advice.", "intermediate"),
    ("eccentric", "adjective", "unconventional and slightly strange", "unusual", "The artist had an eccentric personality that people admired.", "advanced"),
    ("sincere", "adjective", "genuine and honest", "truthful", "He gave a sincere apology for his mistake.", "intermediate"),
    ("ambitious", "adjective", "having a strong desire to achieve something", "aspiring", "She is an ambitious woman who wants to become a CEO.", "intermediate"),
    ("trustworthy", "adjective", "able to be relied on", "reliable", "A good friend should be trustworthy.", "beginner"),
    ("hostile", "adjective", "unfriendly and aggressive", "antagonistic", "The crowd became hostile when the game was cancelled.", "intermediate"),
    ("generous", "adjective", "willing to give and share", "beneficent", "The generous donor helped build a new school.", "beginner"),
    ("negligent", "adjective", "failing to take proper care", "inattentive", "The negligent driver caused the accident.", "advanced"),
    ("compassionate", "adjective", "feeling concern for others", "caring", "A compassionate nurse comforted the worried patient.", "intermediate"),
    ("resilient", "adjective", "able to recover quickly from difficulties", "tough", "Children are surprisingly resilient in the face of hardship.", "advanced"),
    ("assertive", "adjective", "confident and direct in expressing oneself", "self-assured", "Being assertive helps in negotiations.", "advanced"),
    ("meticulous", "adjective", "showing great attention to detail", "thorough", "The meticulous researcher double-checked all the data.", "advanced"),
]

EMOTIONS_FEELINGS = [
    ("ecstasy", "noun", "intense joy or happiness", "joy", "He was filled with ecstasy after hearing the good news.", "advanced"),
    ("jealous", "adjective", "feeling envy toward someone", "envious", "She felt jealous when her friend got promoted.", "beginner"),
    ("misery", "noun", "great suffering or discomfort", "distress", "Losing his job brought him great misery.", "intermediate"),
    ("remorse", "noun", "deep regret for a wrong action", "guilt", "He felt deep remorse for hurting his friend's feelings.", "advanced"),
    ("infuriate", "verb", "to make someone extremely angry", "enrage", "His rude comments infuriated everyone in the room.", "advanced"),
    ("humiliate", "verb", "to make someone feel ashamed", "embarrass", "The teacher should never humiliate a student in front of the class.", "intermediate"),
    ("terror", "noun", "extreme fear", "fright", "She screamed in terror when she saw the spider.", "intermediate"),
    ("comfort", "noun", "a state of physical ease and freedom from pain", "consolation", "His kind words were a great comfort to her.", "beginner"),
    ("grieve", "verb", "to feel intense sorrow", "mourn", "The whole nation grieved the loss of the great leader.", "intermediate"),
    ("anxiety", "noun", "a feeling of worry or unease", "nervousness", "Many students experience anxiety before exams.", "intermediate"),
    ("contentment", "noun", "a state of satisfaction", "satisfaction", "She found contentment in simple daily activities.", "advanced"),
    ("frustration", "noun", "the feeling of being upset due to obstacles", "annoyance", "He expressed frustration with the slow progress.", "intermediate"),
    ("optimistic", "adjective", "expecting the best outcome", "hopeful", "She remained optimistic despite the challenges.", "intermediate"),
    ("pessimistic", "adjective", "expecting the worst outcome", "negative", "Being too pessimistic can affect your motivation.", "intermediate"),
    ("sympathy", "noun", "feelings of pity for someone's misfortune", "compassion", "The community showed sympathy for the affected families.", "intermediate"),
]

ACADEMIC_FORMAL = [
    ("perception", "noun", "the way something is understood", "insight", "Public perception of the issue changed after the report.", "intermediate"),
    ("indisputable", "adjective", "unable to be challenged or denied", "undeniable", "The link between smoking and cancer is indisputable.", "advanced"),
    ("impartial", "adjective", "treating all rivals equally", "neutral", "A good journalist should remain impartial when reporting.", "advanced"),
    ("impediment", "noun", "something that hinders progress", "obstacle", "Lack of funding is the main impediment to progress.", "advanced"),
    ("abstract", "noun", "a summary of a piece of writing", "summary", "The abstract of the research paper explained the key findings.", "advanced"),
    ("substantially", "adverb", "to a great extent", "considerably", "The cost of living has increased substantially in recent years.", "advanced"),
    ("deliberately", "adverb", "intentionally and consciously", "intentionally", "The information was deliberately hidden from the public.", "intermediate"),
    ("priority", "noun", "something regarded as more important than others", "precedence", "Education should be a top priority for every government.", "beginner"),
    ("applicable", "adjective", "relevant or appropriate", "relevant", "This rule is applicable to all employees.", "intermediate"),
    ("imperative", "adjective", "vitally important", "crucial", "It is imperative that we act now to protect the environment.", "advanced"),
    ("moral", "adjective", "concerned with principles of right and wrong", "ethical", "There are moral questions about using animals for testing.", "intermediate"),
    ("momentous", "adjective", "of great importance", "significant", "The election was a momentous event in the country's history.", "advanced"),
    ("catastrophe", "noun", "a great disaster", "disaster", "The oil spill was an environmental catastrophe.", "advanced"),
    ("turmoil", "noun", "a state of great disturbance", "chaos", "The country was in turmoil after the economic crisis.", "advanced"),
    ("repute", "noun", "the opinion people have of someone or something", "reputation", "Harvard is a university of great repute.", "advanced"),
    ("zenith", "noun", "the highest point or peak", "peak", "The empire reached its zenith in the 16th century.", "advanced"),
    ("consecutive", "adjective", "following one after another in order", "successive", "It rained for five consecutive days.", "intermediate"),
    ("appreciable", "adjective", "large enough to be noticed", "considerable", "There has been an appreciable improvement in air quality.", "advanced"),
    ("comprehensible", "adjective", "able to be understood", "understandable", "The instructions should be comprehensible to all readers.", "advanced"),
    ("interplay", "noun", "the way things interact with each other", "interaction", "There is a complex interplay between genetics and environment.", "advanced"),
]

ACTIONS_VERBS = [
    ("accomplish", "verb", "to achieve or complete something", "achieve", "She worked hard to accomplish her goals.", "intermediate"),
    ("disclose", "verb", "to reveal or make known", "reveal", "The company refused to disclose its financial records.", "advanced"),
    ("establish", "verb", "to set up or create", "set up", "They plan to establish a new branch in London.", "intermediate"),
    ("maintain", "verb", "to keep in good condition", "preserve", "It is important to maintain a healthy diet.", "beginner"),
    ("elevate", "verb", "to raise to a higher level", "raise", "Education can elevate people out of poverty.", "intermediate"),
    ("encounter", "verb", "to come across or meet", "come across", "You may encounter some difficulties during the test.", "intermediate"),
    ("evaluate", "verb", "to assess or judge the value of", "assess", "The teacher will evaluate your essay based on four criteria.", "intermediate"),
    ("accumulate", "verb", "to gather or build up", "build up", "Debt can accumulate quickly if you are not careful.", "advanced"),
    ("illuminate", "verb", "to light up or clarify", "clarify", "The professor tried to illuminate the complex topic.", "advanced"),
    ("differentiate", "verb", "to recognize differences", "distinguish", "It is difficult to differentiate between the two species.", "advanced"),
    ("withstand", "verb", "to resist or endure", "resist", "This material can withstand extreme temperatures.", "advanced"),
    ("convey", "verb", "to communicate an idea or feeling", "communicate", "Art can convey powerful messages without words.", "intermediate"),
    ("intensify", "verb", "to become greater or more serious", "heighten", "The storm is expected to intensify over the weekend.", "intermediate"),
    ("transform", "verb", "to change completely", "convert", "Technology has transformed the way we communicate.", "intermediate"),
    ("diminish", "verb", "to decrease or become smaller", "decrease", "The supply of fresh water continues to diminish.", "advanced"),
    ("deduce", "verb", "to infer from evidence", "infer", "From the evidence, we can deduce that the report was accurate.", "advanced"),
    ("visualize", "verb", "to form a mental image", "imagine", "Try to visualize the answer before you write it down.", "intermediate"),
    ("magnify", "verb", "to make something appear larger", "exaggerate", "The media tends to magnify small problems.", "advanced"),
    ("scrutinize", "verb", "to examine closely", "inspect", "The committee will scrutinize the proposal carefully.", "advanced"),
    ("implement", "verb", "to put a plan into effect", "execute", "The government plans to implement the new policy next year.", "intermediate"),
]

POLITICS_GOVERNMENT = [
    ("democracy", "noun", "a system of government by the whole population", "representative government", "Democracy relies on informed citizens voting in elections.", "intermediate"),
    ("legislation", "noun", "laws passed by a government", "law-making", "New legislation was introduced to protect consumer rights.", "advanced"),
    ("policy", "noun", "a course of action adopted by a government", "strategy", "The government's economic policy aims to reduce inflation.", "intermediate"),
    ("bureaucracy", "noun", "a system of government with many rules and processes", "administration", "The bureaucracy can slow down decision-making.", "advanced"),
    ("mandate", "noun", "authority given by voters to a government", "authorization", "The government has a mandate to implement its policies.", "advanced"),
    ("diplomacy", "noun", "the management of international relations", "negotiation", "Diplomacy is essential for maintaining peace between nations.", "advanced"),
    ("referendum", "noun", "a direct vote on a particular issue", "popular vote", "The country held a referendum on the new constitution.", "advanced"),
    ("administration", "noun", "the governing body of a country or organization", "government", "The new administration promised to reform healthcare.", "intermediate"),
    ("coalition", "noun", "a temporary alliance of political parties", "alliance", "The coalition government was formed after the election.", "advanced"),
    ("ideology", "noun", "a system of ideas and beliefs", "philosophy", "Political ideology influences government policy decisions.", "advanced"),
    ("sanction", "noun", "a penalty imposed for breaking a rule", "penalty", "Economic sanctions were imposed on the country.", "advanced"),
    ("sovereignty", "noun", "the authority of a state to govern itself", "self-governance", "The nation fought to maintain its sovereignty.", "advanced"),
]

CRIME_LAW = [
    ("felony", "noun", "a serious crime punishable by imprisonment", "serious crime", "The suspect was charged with a felony.", "advanced"),
    ("misdemeanor", "noun", "a minor wrongdoing", "minor offence", "The offense was classified as a misdemeanor.", "advanced"),
    ("verdict", "noun", "a decision made by a jury", "judgment", "The jury reached a verdict of not guilty.", "intermediate"),
    ("testimony", "noun", "a formal statement given in court", "evidence", "The witness gave a compelling testimony.", "advanced"),
    ("prosecution", "noun", "the legal party bringing charges", "legal action", "The prosecution presented strong evidence.", "advanced"),
    ("defense", "noun", "the case presented by the accused party", "protection", "The defense lawyer argued for his client's innocence.", "intermediate"),
    ("deterrent", "noun", "something that discourages an action", "discouragement", "Long prison sentences act as a deterrent to crime.", "advanced"),
    ("rehabilitation", "noun", "the process of restoring to normal life", "reintegration", "The prison focuses on rehabilitation rather than punishment.", "advanced"),
    ("jurisdiction", "noun", "the official power to    ("jurisdiction", "noun", "the official power to make legal decisions", "authority", "The court has jurisdiction over this case.", "advanced"),
    ("acquittal", "noun", "a judgment that a person is not guilty", "exoneration", "The defendant celebrated his acquittal.", "advanced"),
    ("appeal", "noun", "a request to a higher court to change a decision", "petition", "The lawyer filed an appeal against the sentence.", "advanced"),
    ("arbitration", "noun", "the use of an independent person to settle a dispute", "mediation", "The dispute was settled through arbitration.", "advanced"),
    ("bail", "noun", "temporary release of an accused person awaiting trial", "bond", "The judge set bail at $10,000.", "advanced"),
    ("culprit", "noun", "a person who has committed a crime", "offender", "The police quickly found the culprit.", "intermediate"),
    ("defendant", "noun", "a person accused in a court of law", "accused", "The defendant pleaded not guilty.", "intermediate"),
    ("forensic", "adjective", "relating to scientific methods used in crime investigation", "criminalistic", "Forensic evidence proved crucial to the case.", "advanced"),
    ("indictment", "noun", "a formal charge of a serious crime", "accusation", "The grand jury issued an indictment.", "advanced"),
    ("litigation", "noun", "the process of taking legal action", "lawsuit", "The company faced costly litigation.", "advanced"),
    ("perpetrator", "noun", "a person who carries out a harmful act", "offender", "The perpetrator was arrested at the scene.", "advanced"),
    ("plaintiff", "noun", "a person who brings a case against another in court", "claimant", "The plaintiff demanded compensation for damages.", "advanced"),
    ("recidivism", "noun", "the tendency of a convicted criminal to reoffend", "reoffending", "Programs aimed at reducing recidivism have shown promise.", "advanced"),
    ("sentence", "noun", "the punishment assigned to a convicted person", "penalty", "The judge handed down a five-year sentence.", "intermediate"),
    ("tribunal", "noun", "a body established to settle certain disputes", "court", "The case was heard by an international tribunal.", "advanced"),
]

TASK1_TRENDS = [
    ("increase", "verb", "to become greater in number or size", "rise", "There was a significant increase in sales during the holiday season.", "intermediate"),
    ("decrease", "verb", "to become smaller or fewer", "decline", "The number of visitors decreased sharply in winter.", "intermediate"),
    ("fluctuate", "verb", "to rise and fall irregularly", "vary", "The price of oil fluctuated throughout the year.", "advanced"),
    ("plateau", "verb", "to reach a state of little change after growth", "stabilize", "The population growth plateaued in the 1990s.", "advanced"),
    ("soar", "verb", "to increase rapidly", "surge", "Internet usage soared in the early 2000s.", "advanced"),
    ("plummet", "verb", "to fall or drop straight down quickly", "plunge", "The stock price plummeted after the announcement.", "advanced"),
    ("gradual", "adjective", "taking place slowly over time", "steady", "There was a gradual increase in temperature.", "intermediate"),
    ("dramatic", "adjective", "sudden and striking", "significant", "The graph shows a dramatic rise in unemployment.", "intermediate"),
    ("modest", "adjective", "moderate in size or amount", "moderate", "There was a modest increase in the rate of inflation.", "intermediate"),
    ("peak", "noun", "the highest point", "maximum", "Sales reached a peak in December.", "intermediate"),
    ("trough", "noun", "the lowest point", "minimum", "The economy hit a trough during the recession.", "advanced"),
    ("outstrip", "verb", "to exceed or be greater than", "surpass", "Demand outstripped supply during the holiday period.", "advanced"),
    ("remain_stable", "phrase", "to stay at the same level", "stay constant", "The unemployment rate remained stable throughout the year.", "intermediate"),
    ("upward_trend", "noun", "a general direction of increase", "rising trend", "The chart illustrates an upward trend in exports.", "intermediate"),
    ("downward_trend", "noun", "a general direction of decrease", "declining trend", "There was a downward trend in birth rates.", "intermediate"),
]

SPEAKING_FLUENCY = [
    ("as_far_as_im_concerned", "phrase", "in my opinion", "in my view", "As far as I'm concerned, the government should invest more in education.", "intermediate"),
    ("from_my_perspective", "phrase", "from my point of view", "from my viewpoint", "From my perspective, technology has improved our lives significantly.", "intermediate"),
    ("it_is_worth_noting", "phrase", "it is important to mention", "it should be mentioned", "It is worth noting that the statistics vary by region.", "advanced"),
    ("to_a_certain_extent", "phrase", "partly, but not completely", "to some degree", "To a certain extent, I agree with the proposed changes.", "intermediate"),
    ("the_way_i_see_it", "phrase", "in my opinion", "in my view", "The way I see it, we need to find a balance between work and leisure.", "beginner"),
    ("by_and_large", "phrase", "on the whole", "generally speaking", "By and large, people are satisfied with their quality of life.", "advanced"),
    ("it_goes_without_saying", "phrase", "it is obvious", "clearly", "It goes without saying that education plays a crucial role in development.", "advanced"),
    ("in_other_words", "phrase", "to express the same idea differently", "that is to say", "He is an introvert; in other words, he prefers solitude.", "intermediate"),
    ("take_for_example", "phrase", "for instance", "for example", "Many countries have adopted this policy. Take for example New Zealand.", "intermediate"),
    ("moreover", "adverb", "in addition to what has been said", "furthermore", "The policy is effective. Moreover, it is cost-efficient.", "intermediate"),
    ("nevertheless", "adverb", "in spite of that", "however", "The results were disappointing. Nevertheless, we learned a valuable lesson.", "advanced"),
    ("consequently", "adverb", "as a result", "therefore", "The company lost revenue. Consequently, it had to lay off staff.", "intermediate"),
    ("in_conclusion", "phrase", "to summarize", "to sum up", "In conclusion, the benefits of renewable energy outweigh the costs.", "beginner"),
    ("the_main_point_is", "phrase", "the most important thing is", "the key is", "The main point is that we need to act now.", "intermediate"),
    ("i_strongly_believe", "phrase", "I am convinced that", "I firmly believe", "I strongly believe that education should be free for everyone.", "intermediate"),
]

WORDS_BY_CATEGORY = {
    "environment": ENVIRONMENT,
    "education": EDUCATION,
    "technology": TECHNOLOGY,
    "health": HEALTH,
    "economy-work": ECONOMY_WORK,
    "society-culture": SOCIETY_CULTURE,
    "travel-tourism": TRAVEL_TOURISM,
    "science-research": SCIENCE_RESEARCH,
    "people-personality": PEOPLE_PERSONALITY,
    "emotions-feelings": EMOTIONS_FEELINGS,
    "academic-formal": ACADEMIC_FORMAL,
    "actions-verbs": ACTIONS_VERBS,
    "politics-government": POLITICS_GOVERNMENT,
    "crime-law": CRIME_LAW,
    "task1-trends": TASK1_TRENDS,
    "speaking-fluency": SPEAKING_FLUENCY,
}
